### ISSUE TITLE
[CLI] Error: Update returned exit code not zero

### ISSUE THREAD

**Issue by l34rn1t** [teamdfir/sift#514] opened 2021-03-31 09:25 UTC
[saltstack.log](https://github.com/teamdfir/sift/files/6235438/saltstack.log)

uname -a output:
Linux sift000 4.15.0-112-generic #113~16.04.1-Ubuntu SMP Fri Jul 10 04:37:08 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

LC_ALL=en_US.UTF-8 sudo sift install
> sift-cli@1.9.2
> sift-version: notinstalled

> mode: desktop
> downloading v2021.4.0
>> downloading sift-saltstack-v2021.4.0.tar.gz.asc
>> downloading sift-saltstack-v2021.4.0.tar.gz.sha256
>> downloading sift-saltstack-v2021.4.0.tar.gz.sha256.asc
>> downloading sift-saltstack-v2021.4.0.tar.gz
> validating file sift-saltstack-v2021.4.0.tar.gz
> validating signature for sift-saltstack-v2021.4.0.tar.gz.sha256
[saltstack.log](https://github.com/teamdfir/sift/files/6235439/saltstack.log)

> extracting update sift-saltstack-v2021.4.0.tar.gz
> performing update v2021.4.0
>> Log file: /var/cache/sift/cli/v2021.4.0/saltstack.log

Update returned exit code not zero
Error: Update returned exit code not zero
    at ChildProcess.<anonymous> (/snapshot/sift-cli/sift-cli.js:547:23)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)

----- PLEASE READ ----------------------

A lot of failures are caused by the apt system being locked
or unhealthy. 

Before opening an issue in GitHub, please check to see if 
your apt system is healthy.

Try running 'apt-get update' then remove any packages that 
aren't used by running 'apt-get autoremove'

**Comment by digitalsleuth** [comment] 2021-03-31 16:33
Hi @l34rn1t , Ubuntu 16.04 is no longer a supported OS. Ubuntu 20.04 LTS is the latest supported OS, and would be recommended for your build of SIFT.

**Comment by Xboarder56** [comment] 2021-04-01 21:14
I'm getting this exact error that @l34rn1t is reporting above on ubuntu 20.04 LTS desktop on a fresh install.

**Comment by digitalsleuth** [comment] 2021-04-01 21:17
Hi @Xboarder56 , can you attach your saltstack.log file so we can review it? The error that @l34rn1t received was for a different reason (different OS), so we'll need your log file to determine the cause of the error in your situation.

**Comment by Xboarder56** [comment] 2021-04-01 21:21
@digitalsleuth it's attached below. I tried doing an update and remove without any success either. 
[saltstack.log](https://github.com/teamdfir/sift/files/6246529/saltstack.log)

**Comment by Xboarder56** [comment] 2021-04-01 21:26
@digitalsleuth it looks like there is still a reference to ubuntu 16.04 for the salt packages for powershell as the most likely cause.

**Comment by digitalsleuth** [comment] 2021-04-01 21:35
@Xboarder56 Thanks for uploading the log file. Can you run `cat /etc/os-release` and post the results? The log you attached references states (sift.packages.powershell_xenial) which either no longer exist, or are based on the existing OS (sift.packages.powershell_{{ grains['oscodename'] }}). Somehow saltstack is getting 'xenial' from the environment when it shouldn't especially if you're using Ubuntu 20.04.

**Comment by Xboarder56** [comment] 2021-04-01 21:36
@digitalsleuth below:

sift@siftworkstation: ~
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
sift@siftworkstation: ~
$

**Comment by digitalsleuth** [comment] 2021-04-01 21:37
Thanks. And can you also run `salt-minion -V` and `salt-common -V`? I should have put those in my last comment.

**Comment by Xboarder56** [comment] 2021-04-01 21:42
salt minion returned results, salt-common isn't installed at all.

Salt Minion -V

`sift@siftworkstation: ~
$ salt-minion -V
Salt Version:
          Salt: 3003

Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.11.3
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: 1.1.4
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: 2.6.1
  pycryptodome: 3.10.1
        pygit2: Not Installed
        Python: 3.8.5 (default, Jan 27 2021, 15:41:15)
  python-gnupg: 0.4.5
        PyYAML: 5.3.1
         PyZMQ: 22.0.3
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: ubuntu 20.04 focal
        locale: utf-8
       machine: x86_64
       release: 5.8.0-48-generic
        system: Linux
       version: Ubuntu 20.04 focal

sift@siftworkstation: ~
$`

**Comment by digitalsleuth** [comment] 2021-04-01 21:44
Perfect. Just so you're aware, v3003 of saltstack (common/minion) are not yet supported by SIFT. One easy fix would be to remove 3003 and install 3001, and trying again to see if that works. It's possible there might be an issue caused by the newer version, but I'm going to have to do a little testing to see if that's the issue.

Additionally, salt-common should be installed by the sift-cli by default. Did you use the CLI to install these states, or did you use the salt-minion command?

**Comment by Xboarder56** [comment] 2021-04-01 21:45
Just replied above, but it is installed just the command isn't valid

```sift@siftworkstation: ~
$ sudo apt-get install salt-common
Reading package lists... Done
Building dependency tree
Reading state information... Done
salt-common is already the newest version (3003+ds-1).
0 upgraded, 0 newly installed, 0 to remove and 4 not upgraded.
sift@siftworkstation: ~
$ sudo su
root@siftworkstation:/home/sift# salt-commmon -V
salt-commmon: command not found
root@siftworkstation:/home/sift# salt-
salt-call    salt-minion  salt-proxy
root@siftworkstation:/home/sift# salt-
salt-call    salt-minion  salt-proxy
root@siftworkstation:/home/sift#

**Comment by digitalsleuth** [comment] 2021-04-01 21:47
Strange. Your common command did have too many 'm' 's though. But it's obvious to tell that the salt-(TAB) didn't show the salt-common.

**Comment by Xboarder56** [comment] 2021-04-01 21:57
Just reverted back and got the same error during install. Running 3001.7 now for both minion and common. Really strange it's trying to grab that old package. 

```apt-get remove salt-minnion salt-common
apt-get install salt-common=3001*
apt-get install salt-minnion=3001*

**Comment by ekristen** [comment] 2021-04-01 21:59
You only need salt-common. `salt-call --versions-report`

**Comment by Xboarder56** [comment] 2021-04-01 22:00
salt-call --versions-report

```root@siftworkstation:/home/sift# salt-call --versions-report
Salt Version:
           Salt: 3001.7

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.8.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.11.3
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: 1.1.4
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: 3.10.1
         pygit2: Not Installed
         Python: 3.8.5 (default, Jan 27 2021, 15:41:15)
   python-gnupg: 0.4.5
         PyYAML: 5.3.1
          PyZMQ: 22.0.3
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.4

System Versions:
           dist: ubuntu 20.04 focal
         locale: utf-8
        machine: x86_64
        release: 5.8.0-48-generic
         system: Linux
        version: Ubuntu 20.04 focal

root@siftworkstation:/home/sift#

**Comment by ekristen** [comment] 2021-04-01 22:01
The logs here https://github.com/teamdfir/sift/issues/514#issuecomment-812179829 failed on a powershell install, it resolved to install for xenial, but clearly you are on 20.04.

**Comment by Xboarder56** [comment] 2021-04-01 22:04
@ekristen is there a way to manually install powershell for it to continue the reset of the installation.

**Comment by digitalsleuth** [comment] 2021-04-01 22:10
You can install Powershell manually, but that state will still try to install it for Xenial until we figure out why it's looking for xenial instead of focal.

**Comment by ekristen** [comment] 2021-04-01 22:11
Can you please do another install and provide the log.

**Comment by Xboarder56** [comment] 2021-04-01 22:21
@ekristen I moved the old log to a new file, and just executed the install again.

[saltstack.log](https://github.com/teamdfir/sift/files/6246739/saltstack.log)

**Comment by ekristen** [comment] 2021-04-01 22:27
Looks like your apt database is busted and possible issues with python too.

Please run an `apt-get update && apt-get upgrade`.

Was this an upgraded OS? Like did you upgrade from xenial to focal? Did you previously have sift installed?

**Comment by Xboarder56** [comment] 2021-04-01 22:42
no this is a pure fresh install from an ISO 20.04 and upgraded to 20.04.2

command results below:
```root@siftworkstation:/var/cache/sift/cli/v2021.4.1#
root@siftworkstation:/var/cache/sift/cli/v2021.4.1#
root@siftworkstation:/var/cache/sift/cli/v2021.4.1# apt-get update && apt-get upgrade
Hit:1 https://download.docker.com/linux/ubuntu focal InRelease
Hit:2 http://repo.saltstack.com/py3/ubuntu/20.04/amd64/3001 focal InRelease
Hit:3 http://us.archive.ubuntu.com/ubuntu focal InRelease
Get:4 http://us.archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]
Hit:5 http://ppa.launchpad.net/gift/stable/ubuntu focal InRelease
Get:6 http://security.ubuntu.com/ubuntu focal-security InRelease [109 kB]
Hit:7 http://archive.ubuntu.com/ubuntu focal InRelease
Hit:8 https://repo.saltproject.io/py3/ubuntu/20.04/amd64/latest focal InRelease
Get:9 http://archive.ubuntu.com/ubuntu focal-security InRelease [109 kB]
Hit:10 http://ppa.launchpad.net/openjdk-r/ppa/ubuntu focal InRelease
Get:11 http://us.archive.ubuntu.com/ubuntu focal-backports InRelease [101 kB]
Hit:12 http://ppa.launchpad.net/sift/dev/ubuntu focal InRelease
Fetched 433 kB in 1s (429 kB/s)
Reading package lists... Done
N: Skipping acquire of configured file 'main/binary-i386/Packages' as repository 'https://repo.saltproject.io/py3/ubuntu/20.04/amd64/latest focal InRelease' doesn't support architecture 'i386'
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
The following packages have been kept back:
  python3-cryptography ubuntu-desktop ubuntu-desktop-minimal ubuntu-drivers-common
The following packages will be upgraded:
  salt-common salt-minion
2 upgraded, 0 newly installed, 0 to remove and 4 not upgraded.
Need to get 0 B/7,156 kB of archives.
After this operation, 225 kB of additional disk space will be used.
Do you want to continue? [Y/n]

**Comment by digitalsleuth** [comment] 2021-04-01 22:50
@Xboarder56 Out of curiosity, did you use the Ubuntu Server ISO or the Desktop ISO? And if server, did you install the desktop environment, and which one did you choose?

**Comment by Xboarder56** [comment] 2021-04-01 22:54
I used the standard desktop iso. I can get you a hash of it @digitalsleuth

**Comment by digitalsleuth** [comment] 2021-04-01 22:56
No that's good. I don't doubt you're using the right one, I'm just trying to duplicate the error to figure out what happened. I'm using the 20.04.2.0-desktop ISO and no problem.

**Comment by Xboarder56** [comment] 2021-04-01 23:01
ubuntu-20.04-desktop-amd64 MD5: EA28C4FD933BE55F9F01A5FA9E868490

just in case. I did a default installed username was sift, and I did install updates and 3rd party add ons.

**Comment by digitalsleuth** [comment] 2021-04-01 23:49
@Xboarder56 I'm trying to duplicate the issues, but something doesn't seem to fit, and I'm wondering if you can help me sort out some problems. Saltstack isn't installed in the default Ubuntu 20.04 release, and on a clean install, the sift-cli installs the 3001 release. You stated at the beginning, after posting your saltstack.log, that you had version 3003 installed. The log you provided at the time also had Xenial references to it, which it ideally shouldn't.

Can you walk me through, step by step, what process you followed?

I've looked at the first three saltstack.log files here (https://github.com/teamdfir/sift/files/6235438/saltstack.log, https://github.com/teamdfir/sift/files/6235439/saltstack.log - both from @l34rn1t, and https://github.com/teamdfir/sift/files/6246529/saltstack.log from you) and all three of those have the same MD5. The first two should have the same MD5 if uploaded from the same person at the same time. But the one you posted has the same MD5 as @l34rn1t's log files, and it shouldn't. 

Perhaps this might be an accident, but it would help us if we could recreate the steps you took to duplicate the error you're receiving.

**Comment by Xboarder56** [comment] 2021-04-02 00:00
So I think I know why this occurred @digitalsleuth a fresh install did work correctly.

At the start I was gonna launch the salt stack version as a stand alone without the cli tools. So I went to salt stacks website and added the gpg key and installed salt stack manually using the below commands. Once this was done I manually installed salt stack minion using apt-get install salt-minion. Then I manually launched sift-salt-stack using the command listed in the repo and it just hung. That's when I transitioned over to the cli installation method. 

```# Download key
sudo curl -fsSL -o /usr/share/keyrings/salt-archive-keyring.gpg https://repo.saltproject.io/py3/ubuntu/20.04/amd64/latest/salt-archive-keyring.gpg
# Create apt sources list file
echo "deb [signed-by=/usr/share/keyrings/salt-archive-keyring.gpg] https://repo.saltproject.io/py3/ubuntu/20.04/amd64/latest focal main" | sudo tee /etc/apt/sources.list.d/salt.list

**Comment by digitalsleuth** [comment] 2021-04-02 00:03
That makes some sense. There have been some recent changes with the way saltstack handles their repo, (saltproject.io vice saltstack.com) and using the `latest` keyword in the installation installed the latest version (`3003`).

Glad to hear you got this resolved and have a working installation.

**Comment by ekristen** [comment] 2021-04-03 01:15
@Xboarder56 are we good to close this?

**Comment by Xboarder56** [comment] 2021-04-03 01:18
Yes @ekristen this is good To go. Thanks for the help guys.

**Closed** 2021-04-03 01:30 UTC
