### ISSUE TITLE
Jinja2 Markup error during SIFT CLI install

### ISSUE THREAD

**Issue by bhamdans** [teamdfir/sift#559] opened 2022-04-18 14:02 UTC
> sift-cli@1.14.0-rc1+0-g0582d2b
> sift-version: notinstalled

> mode: server
> downloading v2022.01.22
>> downloading sift-saltstack-v2022.01.22.tar.gz.asc
>> downloading sift-saltstack-v2022.01.22.tar.gz.sha256
>> downloading sift-saltstack-v2022.01.22.tar.gz.sha256.asc
>> downloading sift-saltstack-v2022.01.22.tar.gz
> validating file sift-saltstack-v2022.01.22.tar.gz
> validating signature for sift-saltstack-v2022.01.22.tar.gz.sha256
> extracting update sift-saltstack-v2022.01.22.tar.gz
> performing update v2022.01.22
>> Log file: /var/cache/sift/cli/v2022.01.22/saltstack.log

Update returned exit code not zero
Error: Update returned exit code not zero
    at ChildProcess.<anonymous> (/snapshot/sift-cli/sift-cli.js:556:23)
    at ChildProcess.emit (events.js:400:28)
    at maybeClose (internal/child_process.js:1058:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)
--------------------------------------------------------------------------------------
From  saltstack.log:
-- snip -- 
 File "/usr/lib/python3/dist-packages/salt/utils/jinja.py", line 28, in <module>
    from jinja2 import BaseLoader, Markup, TemplateNotFound, nodes
ImportError: cannot import name 'Markup' from 'jinja2' (/usr/local/lib/python3.8/dist-packages/jinja2/__init__.py)

**Comment by digitalsleuth** [comment] 2022-04-18 14:53
Hi @bhamdans This is caused by a change in Salt 3004 which upgrades the Jinja package. You can rectify this temporarily by running `sudo python3 -m pip install jinja2==3.0.3` then running the command again. 

I'll submit a PR later today which will fix this issue for the SIFT install.

**Comment by bhamdans** [comment] 2022-04-18 15:28
Testing now.

-=Dan=-

**Comment by digitalsleuth** [comment] 2022-05-31 02:10
Hi @bhamdans has this issue been resolved for you?

**Comment by ekristen** [comment] 2023-02-01 23:35
Please also note, that once https://github.com/teamdfir/sift-saltstack/pull/80 is merged, SIFT CLI will be officially deprecated as of March 1, 2023, and is replaced with [cast](https://github.com/ekristen/cast)

**Closed by ekristen** 2023-02-01 23:35 UTC
