### ISSUE TITLE
Issue installing v2019.12.0

### ISSUE THREAD

**Issue by Queen-Nahla** [teamdfir/sift#419] opened 2019-12-26 22:20 UTC
I'm trying to install SIFT v2019.12.0 on Ubuntu desktop 16.04. At the end of the installation I receive the following errors: 

Update returned exit code not zero
Error: Update returned exit code not zero
    at ChildProcess.update.on (/snapshot/sift-cli/sift-cli.js:488:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

I've updated pyOpenSSL per the same problem in a previous issue, but still receive the same thing. Please advise.

**Comment by ekristen** [comment] 2019-12-26 22:30
Please attach your saltstack.log and the more of the output of the CLI tool.

**Comment by ekristen** [comment] 2019-12-26 22:30
I would also suggest trying 18.04 if you are trying to install fresh.

**Comment by Queen-Nahla** [comment] 2019-12-27 16:57
Hi Erik,

I’ve tried on 16.04 and 18.04 and am getting the same results on both.

The  saltstack log from 18.04 and the install output are attached. Thank you so much for the quick response!

Kristen

**Comment by ekristen** [comment] 2019-12-27 17:41
Please attach /var/cache/sift/cli/v2019.12.0/saltstack.log <--

Also please provide me with which version of the CLI  you are using. You are the only one to report this and I cannot reproduce it.

**Comment by Queen-Nahla** [comment] 2019-12-27 17:53
The saltstack.log I attached in my previous email is from /var/cache/sift/cli/v2019.12.0. In case it got stripped or something, I’ve attached it again.

This issue is occurring on AWS AMIs. As previously mentioned, I’ve tried Ubuntu server 16.04 and Ubuntu desktop 16.04 & 18.04. All of them have the same errors at the end of the install.

I’m running the wget commands from here to get the files:   https://gist.github.com/jermdw/4dd16bceef8d032acda81907511e9099
After which I’m following steps 6 and 7 from here: https://github.com/teamdfir/sift-cli

Thank you

**Comment by Queen-Nahla** [comment] 2019-12-27 17:54
Sorry, the cli version is 1.5.1-beta.0-master.154cb2f

From: Kristen Fettig
Sent: Friday, December 27, 2019 12:53 PM
To: teamdfir/sift <reply@reply.github.com>; teamdfir/sift <sift@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: RE: [teamdfir/sift] Issue installing v2019.12.0 (#419)

The saltstack.log I attached in my previous email is from /var/cache/sift/cli/v2019.12.0. In case it got stripped or something, I’ve attached it again.

This issue is occurring on AWS AMIs. As previously mentioned, I’ve tried Ubuntu server 16.04 and Ubuntu desktop 16.04 & 18.04. All of them have the same errors at the end of the install.

I’m running the wget commands from here to get the files:   https://gist.github.com/jermdw/4dd16bceef8d032acda81907511e9099
After which I’m following steps 6 and 7 from here: https://github.com/teamdfir/sift-cli

Thank you

**Comment by ekristen** [comment] 2019-12-27 18:06
Please upgrade to the latest version of the CLI.

**Comment by Queen-Nahla** [comment] 2019-12-27 18:07
Just did when I saw I was behind. I’m trying the install again now. Thank you

**Comment by Queen-Nahla** [comment] 2019-12-27 18:25
This is what happens after updating the cli:


>> Incomplete due to Failures -- Success: 547, Failure: 4

>>>> List of Failures (first 10 only)

     NOTE: First failure is generally the root cause.

     IMPORTANT: If opening a ticket, please include this information.

      - ID: sift-scripts-cyberchef-index
        SLS: sift.scripts.cyberchef
        Run#: 335
        Comment: The target file "/var/www/html/cyberchef/index.html" exists and will not be overwritten
      - ID: undefined
        SLS: sift.scripts
        Run#: 453
        Comment: One or more requisite failed: sift.scripts.cyberchef.sift-scripts-cyberchef-index
      - ID: undefined
        SLS: sift.server
        Run#: 454
        Comment: One or more requisite failed: sift.scripts.sift-scripts
      - ID: undefined
        SLS: sift.desktop
        Run#: 557
        Comment: One or more requisite failed: sift.server.sift-server-version-file

New log is attached

**Comment by Queen-Nahla** [comment] 2019-12-30 21:38
Hi,

Any updates/comments?

Thanks,
Kristen

From: Kristen Fettig
Sent: Friday, December 27, 2019 1:26 PM
To: teamdfir/sift <reply@reply.github.com>; teamdfir/sift <sift@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: RE: [teamdfir/sift] Issue installing v2019.12.0 (#419)

This is what happens after updating the cli:


>> Incomplete due to Failures -- Success: 547, Failure: 4

>>>> List of Failures (first 10 only)

     NOTE: First failure is generally the root cause.

     IMPORTANT: If opening a ticket, please include this information.

      - ID: sift-scripts-cyberchef-index
        SLS: sift.scripts.cyberchef
        Run#: 335
        Comment: The target file "/var/www/html/cyberchef/index.html" exists and will not be overwritten
      - ID: undefined
        SLS: sift.scripts
        Run#: 453
        Comment: One or more requisite failed: sift.scripts.cyberchef.sift-scripts-cyberchef-index
      - ID: undefined
        SLS: sift.server
        Run#: 454
        Comment: One or more requisite failed: sift.scripts.sift-scripts
      - ID: undefined
        SLS: sift.desktop
        Run#: 557
        Comment: One or more requisite failed: sift.server.sift-server-version-file

New log is attached

**Comment by ekristen** [comment] 2019-12-31 04:44
It’s 99% installed so that’s the good news.

Try the latest release, it should be fixed. 

Erik

**Comment by Queen-Nahla** [comment] 2019-12-31 17:05
I’ve encountered some issues with the python venv and since both 2 and 3 are installed, I’ve set the primary version to 3.6.9.
This is what I’m getting when I’m attempting the upgrade: (new log attached)

>> Incomplete due to Failures -- Success: 543, Failure: 8

>>>> List of Failures (first 10 only)

     NOTE: First failure is generally the root cause.

     IMPORTANT: If opening a ticket, please include this information.

      - ID: appcompatprocessor
       SLS: sift.python-packages.appcompatprocessor
        Run#: 226
        Comment: Failed to install packages: git+https://github.com/mbevilacqua/appcompatprocessor.git@46ba76a73fcf71640f2a6e9db02afaaac3e178b9. Error: Collecting git+https://github.com/mbevilacqua/appcompatprocessor.git@46ba76a73fcf71640f2a6e9db02afaaac3e178b9
  Cloning https://github.com/mbevilacqua/appcompatprocessor.git (to 46ba76a73fcf71640f2a6e9db02afaaac3e178b9) to /tmp/pip-23ivq28f-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-23ivq28f-build/setup.py", line 4, in <module>
        from settings import __version__
      File "/tmp/pip-23ivq28f-build/settings.py", line 9, in <module>
        from Queue import Empty
    ModuleNotFoundError: No module named 'Queue'

    ----------------------------------------   Could not find a tag or branch '46ba76a73fcf71640f2a6e9db02afaaac3e178b9', assuming commit.
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-23ivq28f-build/
      - ID: sift-python-packages-defang
        SLS: sift.python-packages.defang
        Run#: 236
        Comment: Error installing 'defang==0.5.2': Access denied to /usr/bin/pip3, could not find a pip binary
      - ID: sift-python-packages-machinae
        SLS: sift.python-packages.machinae
        Run#: 237
        Comment: Error installing 'machinae': Access denied to /usr/bin/pip3, could not find a pip binary
      - ID: undefined
        SLS: sift.python-packages
        Run#: 289
        Comment: One or more requisite failed: sift.python-packages.appcompatprocessor.appcompatprocessor
      - ID: sift-scripts-cyberchef-index
        SLS: sift.scripts.cyberchef
        Run#: 335
        Comment: The target file "/var/www/html/cyberchef/index.html" exists and will not be overwritten
      - ID: undefined
        SLS: sift.scripts
        Run#: 453
        Comment: One or more requisite failed: sift.scripts.cyberchef.sift-scripts-cyberchef-index
      - ID: undefined
        SLS: sift.server
        Run#: 454
        Comment: One or more requisite failed: sift.scripts.sift-scripts, sift.python-packages.sift-python-packages
      - ID: undefined
        SLS: sift.desktop
        Run#: 557
        Comment: One or more requisite failed: sift.server.sift-server-version-file
ubuntu@siftworkstation: /usr/bin
$

**Comment by mrh1** [comment] 2020-01-01 23:31
> It’s 99% installed so that’s the good news. Try the latest release, it should be fixed. Erik
> 

I just installed a fresh Ubuntu 18.04 as a VM in VirtualBox, did an apt install and upgrade, then downloaded and ran the latest CLI 1.8. First, it failed due to a network problem (when trying to install wine). I re-ran the install, and it failed with the same error that Queen-Nahla reported.

I removed the /var/www/html/cyberchef/index.html file and reran the install. That completed successfully.

> Incomplete due to Failures -- Success: 547, Failure: 4
>>> List of Failures (first 10 only)
NOTE: First failure is generally the root cause.

     IMPORTANT: If opening a ticket, please include this information.

      - ID: sift-scripts-cyberchef-index
        SLS: sift.scripts.cyberchef
        Run#: 335
        Comment: The target file "/var/www/html/cyberchef/index.html" exists and will not be overwritten
      - ID: undefined
        SLS: sift.scripts
        Run#: 453
        Comment: One or more requisite failed: sift.scripts.cyberchef.sift-scripts-cyberchef-index
      - ID: undefined
        SLS: sift.server
        Run#: 454
        Comment: One or more requisite failed: sift.scripts.sift-scripts
      - ID: undefined
        SLS: sift.desktop
        Run#: 557
        Comment: One or more requisite failed: sift.server.sift-server-version-file

**Comment by ekristen** [comment] 2020-01-05 00:24
That bug should have already been addressed. I’ll test again tonight.

**Comment by Queen-Nahla** [comment] 2020-01-07 15:35
Hi,

Any updates? I’m getting the same error message:

>> Incomplete due to Failures -- Success: 543, Failure: 8

>>>> List of Failures (first 10 only)

     NOTE: First failure is generally the root cause.

     IMPORTANT: If opening a ticket, please include this information.

      - ID: appcompatprocessor
        SLS: sift.python-packages.appcompatprocessor
        Run#: 226
        Comment: Failed to install packages: git+https://github.com/mbevilacqua/appcompatprocessor.git@46ba76a73fcf71640f2a6e9db02afaaac3e178b9. Error: Collecting git+https://github.com/mbevilacqua/appcompatprocessor.git@46ba76a73fcf71640f2a6e9db02afaaac3e178b9
  Cloning https://github.com/mbevilacqua/appcompatprocessor.git (to 46ba76a73fcf71640f2a6e9db02afaaac3e178b9) to /tmp/pip-q43e41mf-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-q43e41mf-build/setup.py", line 4, in <module>
        from settings import __version__
      File "/tmp/pip-q43e41mf-build/settings.py", line 9, in <module>
        from Queue import Empty
    ModuleNotFoundError: No module named 'Queue'

**Comment by ekristen** [comment] 2020-01-07 16:44
The latest solves it. v2020.1.0

**Comment by Queen-Nahla** [comment] 2020-01-07 22:57
Hi,

Unfortunately still getting the same/similar error when attempting to upgrade to latest version. Latest log attached.

>> Incomplete due to Failures -- Success: 551, Failure: 6

>>>> List of Failures (first 10 only)

     NOTE: First failure is generally the root cause.

     IMPORTANT: If opening a ticket, please include this information.

      - ID: appcompatprocessor
        SLS: sift.python-packages.appcompatprocessor
        Run#: 226
        Comment: Failed to install packages: git+https://github.com/mbevilacqua/appcompatprocessor.git@46ba76a73fcf71640f2a6e9db02afaaac3e178b9. Error: Collecting git+https://github.com/mbevilacqua/appcompatprocessor.git@46ba76a73fcf71640f2a6e9db02afaaac3e178b9
  Cloning https://github.com/mbevilacqua/appcompatprocessor.git (to 46ba76a73fcf71640f2a6e9db02afaaac3e178b9) to /tmp/pip-treg2cr4-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-treg2cr4-build/setup.py", line 4, in <module>
        from settings import __version__
      File "/tmp/pip-treg2cr4-build/settings.py", line 9, in <module>
        from Queue import Empty
    ModuleNotFoundError: No module named 'Queue'

    ----------------------------------------   Could not find a tag or branch '46ba76a73fcf71640f2a6e9db02afaaac3e178b9', assuming commit.
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-treg2cr4-build/
      - ID: sift-python-packages-defang
        SLS: sift.python-packages.defang
        Run#: 236
        Comment: Error installing 'defang==0.5.2': Access denied to /usr/bin/pip3, could not find a pip binary
      - ID: sift-python-packages-machinae
        SLS: sift.python-packages.machinae
        Run#: 237
        Comment: Error installing 'machinae': Access denied to /usr/bin/pip3, could not find a pip binary
      - ID: undefined
        SLS: sift.python-packages
        Run#: 289
        Comment: One or more requisite failed: sift.python-packages.appcompatprocessor.appcompatprocessor
      - ID: undefined
        SLS: sift.server
        Run#: 460
        Comment: One or more requisite failed: sift.python-packages.sift-python-packages
      - ID: undefined
        SLS: sift.desktop
        Run#: 563
        Comment: One or more requisite failed: sift.server.sift-server-version-file

**Comment by Queen-Nahla** [comment] 2020-01-14 18:21
Hello,

Any updates?

Thank you,
Kristen

From: Kristen Fettig
Sent: Tuesday, January 7, 2020 5:57 PM
To: teamdfir/sift <reply@reply.github.com>; teamdfir/sift <sift@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: RE: [teamdfir/sift] Issue installing v2019.12.0 (#419)

Hi,

Unfortunately still getting the same/similar error when attempting to upgrade to latest version. Latest log attached.

>> Incomplete due to Failures -- Success: 551, Failure: 6

>>>> List of Failures (first 10 only)

     NOTE: First failure is generally the root cause.

     IMPORTANT: If opening a ticket, please include this information.

      - ID: appcompatprocessor
        SLS: sift.python-packages.appcompatprocessor
        Run#: 226
        Comment: Failed to install packages: git+https://github.com/mbevilacqua/appcompatprocessor.git@46ba76a73fcf71640f2a6e9db02afaaac3e178b9. Error: Collecting git+https://github.com/mbevilacqua/appcompatprocessor.git@46ba76a73fcf71640f2a6e9db02afaaac3e178b9
  Cloning https://github.com/mbevilacqua/appcompatprocessor.git (to 46ba76a73fcf71640f2a6e9db02afaaac3e178b9) to /tmp/pip-treg2cr4-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-treg2cr4-build/setup.py", line 4, in <module>
        from settings import __version__
      File "/tmp/pip-treg2cr4-build/settings.py", line 9, in <module>
        from Queue import Empty
    ModuleNotFoundError: No module named 'Queue'

    ----------------------------------------   Could not find a tag or branch '46ba76a73fcf71640f2a6e9db02afaaac3e178b9', assuming commit.
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-treg2cr4-build/
      - ID: sift-python-packages-defang
        SLS: sift.python-packages.defang
        Run#: 236
        Comment: Error installing 'defang==0.5.2': Access denied to /usr/bin/pip3, could not find a pip binary
      - ID: sift-python-packages-machinae
        SLS: sift.python-packages.machinae
        Run#: 237
        Comment: Error installing 'machinae': Access denied to /usr/bin/pip3, could not find a pip binary
      - ID: undefined
        SLS: sift.python-packages
        Run#: 289
        Comment: One or more requisite failed: sift.python-packages.appcompatprocessor.appcompatprocessor
      - ID: undefined
        SLS: sift.server
        Run#: 460
        Comment: One or more requisite failed: sift.python-packages.sift-python-packages
      - ID: undefined
        SLS: sift.desktop
        Run#: 563
        Comment: One or more requisite failed: sift.server.sift-server-version-file

**Comment by mrh1** [comment] 2020-01-16 00:06
Kristen,
Erik Kristensen said this in a January 7 email:
The latest solves it. v2020.1.0

   I don't see that as a release yet, though.

-Mark
 
On Tuesday, January 14, 2020, 10:21:33 AM PST, Queen-Nahla <notifications@github.com> wrote:  
 
 Hello,

Any updates?

Thank you,
Kristen

From: Kristen Fettig
Sent: Tuesday, January 7, 2020 5:57 PM
To: teamdfir/sift <reply@reply.github.com>; teamdfir/sift <sift@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: RE: [teamdfir/sift] Issue installing v2019.12.0 (#419)

Hi,

Unfortunately still getting the same/similar error when attempting to upgrade to latest version. Latest log attached.

>> Incomplete due to Failures -- Success: 551, Failure: 6

>>>> List of Failures (first 10 only)

 NOTE: First failure is generally the root cause.

 IMPORTANT: If opening a ticket, please include this information.

 - ID: appcompatprocessor
 SLS: sift.python-packages.appcompatprocessor
 Run#: 226
 Comment: Failed to install packages: git+https://github.com/mbevilacqua/appcompatprocessor.git@46ba76a73fcf71640f2a6e9db02afaaac3e178b9. Error: Collecting git+https://github.com/mbevilacqua/appcompatprocessor.git@46ba76a73fcf71640f2a6e9db02afaaac3e178b9
 Cloning https://github.com/mbevilacqua/appcompatprocessor.git (to 46ba76a73fcf71640f2a6e9db02afaaac3e178b9) to /tmp/pip-treg2cr4-build
 Complete output from command python setup.py egg_info:
 Traceback (most recent call last):
 File "<string>", line 1, in <module>
 File "/tmp/pip-treg2cr4-build/setup.py", line 4, in <module>
 from settings import __version__
 File "/tmp/pip-treg2cr4-build/settings.py", line 9, in <module>
 from Queue import Empty
 ModuleNotFoundError: No module named 'Queue'

 ---------------------------------------- Could not find a tag or branch '46ba76a73fcf71640f2a6e9db02afaaac3e178b9', assuming commit.
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-treg2cr4-build/
 - ID: sift-python-packages-defang
 SLS: sift.python-packages.defang
 Run#: 236
 Comment: Error installing 'defang==0.5.2': Access denied to /usr/bin/pip3, could not find a pip binary
 - ID: sift-python-packages-machinae
 SLS: sift.python-packages.machinae
 Run#: 237
 Comment: Error installing 'machinae': Access denied to /usr/bin/pip3, could not find a pip binary
 - ID: undefined
 SLS: sift.python-packages
 Run#: 289
 Comment: One or more requisite failed: sift.python-packages.appcompatprocessor.appcompatprocessor
 - ID: undefined
 SLS: sift.server
 Run#: 460
 Comment: One or more requisite failed: sift.python-packages.sift-python-packages
 - ID: undefined
 SLS: sift.desktop
 Run#: 563
 Comment: One or more requisite failed: sift.server.sift-server-version-file

**Comment by mrh1** [comment] 2020-01-16 00:07
Is that a new release, or will be release 4.8? Or do you mean the latest checked-in software fixes the problem, but I need to build it myself?

    On Tuesday, January 7, 2020, 8:44:14 AM PST, Erik Kristensen <notifications@github.com> wrote:  
 
 
The latest solves it. v2020.1.0

**Comment by mrh1** [comment] 2020-01-16 01:49
Or did you mean the latest version of SIFT?

    On Tuesday, January 7, 2020, 8:44:14 AM PST, Erik Kristensen <notifications@github.com> wrote:  
 
 
The latest solves it. v2020.1.0

**Comment by Queen-Nahla** [comment] 2020-01-16 13:14
When running sift install or sift upgrade the version being installed is v2020.1.0, but I'm still getting the same/similar message: 

 - ID: appcompatprocessor
 SLS: sift.python-packages.appcompatprocessor
 Run#: 226
 Comment: Failed to install packages: git+https://github.com/mbevilacqua/appcompatprocessor.git@46ba76a73fcf71640f2a6e9db02afaaac3e178b9. Error: Collecting git+https://github.com/mbevilacqua/appcompatprocessor.git@46ba76a73fcf71640f2a6e9db02afaaac3e178b9
 Cloning https://github.com/mbevilacqua/appcompatprocessor.git (to 46ba76a73fcf71640f2a6e9db02afaaac3e178b9) to /tmp/pip-treg2cr4-build
 Complete output from command python setup.py egg_info:
 Traceback (most recent call last):
 File "<string>", line 1, in <module>
 File "/tmp/pip-treg2cr4-build/setup.py", line 4, in <module>
 from settings import __version__
 File "/tmp/pip-treg2cr4-build/settings.py", line 9, in <module>
 from Queue import Empty
 ModuleNotFoundError: No module named 'Queue'

**Comment by mrh1** [comment] 2020-01-16 13:41
Perhaps I've mixed up the responses for different issues. Are you having a problem with sift-cli, Rekall or with sleuthkit-java? 
    On Thursday, January 16, 2020, 05:14:37 AM PST, Queen-Nahla <notifications@github.com> wrote:  
 
 
When running sift install or sift upgrade the version being installed is v2020.1.0, but I'm still getting the same/similar message:
   
   - ID: appcompatprocessor   
SLS: sift.python-packages.appcompatprocessor   
Run#: 226   
Comment: Failed to install packages: git+https://github.com/mbevilacqua/appcompatprocessor.git@46ba76a73fcf71640f2a6e9db02afaaac3e178b9. Error: Collecting git+https://github.com/mbevilacqua/appcompatprocessor.git@46ba76a73fcf71640f2a6e9db02afaaac3e178b9   
Cloning https://github.com/mbevilacqua/appcompatprocessor.git (to 46ba76a73fcf71640f2a6e9db02afaaac3e178b9) to /tmp/pip-treg2cr4-build   
Complete output from command python setup.py egg_info:   
Traceback (most recent call last):   
File "", line 1, in    
File "/tmp/pip-treg2cr4-build/setup.py", line 4, in    
from settings import version   
File "/tmp/pip-treg2cr4-build/settings.py", line 9, in    
from Queue import Empty   
ModuleNotFoundError: No module named 'Queue'

**Comment by Queen-Nahla** [comment] 2020-01-16 14:03
My issue is that I can't get the SIFT workstation to install. Haven't made it to the point of being able to use it.

**Comment by mrh1** [comment] 2020-01-19 00:27
Did you try to install it after a clean install of Ubuntu Linux? I had no problems when I first created a new Ubuntu 18.04, did all of the updates/upgrades, then downloaded and ran sift-cli.

    On Thursday, January 16, 2020, 6:03:04 AM PST, Queen-Nahla <notifications@github.com> wrote:  
 
 
My issue is that I can't get the SIFT workstation to install. Haven't made it to the point of being able to use it.

**Comment by Queen-Nahla** [comment] 2020-01-21 12:32
Yes. I’m attempting this in AWS, though, so that must make a difference. I’ve tried 6 different AMIs of 18.04 and 16.04 and have had issues on all of them. Is it possible to install an older version of SIFT? This was done in the past (2017/2018) by a previous colleague. Unfortunately no one can authenticate to the instance he built because we don’t have his keys.

**Comment by ekristen** [comment] 2020-01-21 13:23
We have a prebuilt AMI you can test.

https://github.com/teamdfir/sift/issues/407#issuecomment-569567335

Only in us-west-2 at the moment.

**Comment by Queen-Nahla** [comment] 2020-01-21 13:30
Cool, thanks! I’ll check it out today.

**Comment by ekristen** [comment] 2020-02-11 04:23
Issue maintenance. Closing. Seems like the issue is likely resolved. If you are still having issues please install the latest version of the CLI and install the latest version of SIFT using it.

**Closed by ekristen** 2020-02-11 04:23 UTC
