### ISSUE TITLE
libtsk issue

### ISSUE THREAD

**Issue by zappeee** [teamdfir/sift#361] opened 2019-04-05 14:42 UTC
I got this issue after updating today.

```
>>>> List of Failures (first 10 only)

     NOTE: First failure is generally the root cause.

     IMPORTANT: If opening a ticket, please include this information.

      - ID: sleuthkit
        SLS: sift.packages.sleuthkit
        Run#: 221
        Comment: An error was encountered while installing package(s): Problem encountered installing package(s). Additional info follows:

changes:
    ----------
    sleuthkit:
        ----------
        new:
        old:
            4.6.5-1sift5~xenial
errors:
    - Running scope as unit run-rf6e27ea567ff40c1adb8f36915cfdb96.scope.
      E: Sub-process /usr/bin/dpkg returned an error code (1)
      - ID: sift-wine-apt-update
        SLS: sift.packages.wine
        Run#: 249
        Comment: Failed to get upgrades: E: Unmet dependencies. Try using -f.
      - ID: undefined
        SLS: sift.packages.wine
        Run#: 250
        Comment: One or more requisite failed: sift.packages.wine.sift-wine-apt-update
      - ID: undefined
        SLS: sift.packages
        Run#: 257
        Comment: One or more requisite failed: sift.packages.wine.sift-wine, sift.packages.sleuthkit.sleuthkit, sift.packages.wine.sift-wine-apt-update
      - ID: undefined
        SLS: sift.vm
        Run#: 548
        Comment: One or more requisite failed: sift.packages.sift-packages
```

So I tried that
```

$ sudo apt-get -f install
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Correcting dependencies... Done
The following additional packages will be installed:
  libtsk13
The following NEW packages will be installed:
  libtsk13
0 upgraded, 1 newly installed, 0 to remove and 20 not upgraded.
1 not fully installed or removed.
Need to get 808 kB of archives.
After this operation, 3,741 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://ppa.launchpad.net/gift/stable/ubuntu xenial/main amd64 libtsk13 amd64 4.6.5-2ppa1~xenial [808 kB]
Fetched 808 kB in 1s (711 kB/s)     
(Reading database ... 345244 files and directories currently installed.)
Preparing to unpack .../libtsk13_4.6.5-2ppa1~xenial_amd64.deb ...
Unpacking libtsk13 (4.6.5-2ppa1~xenial) ...
dpkg: error processing archive /var/cache/apt/archives/libtsk13_4.6.5-2ppa1~xenial_amd64.deb (--unpack):
 trying to overwrite '/usr/lib/libtsk.so.13.4.6', which is also in package libtsk 4.6.5-1sift5~xenial
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
Processing triggers for libc-bin (2.23-0ubuntu11) ...
/sbin/ldconfig.real: /usr/lib/libpff.so.1 is not a symbolic link

Errors were encountered while processing:
 /var/cache/apt/archives/libtsk13_4.6.5-2ppa1~xenial_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

How can I get libtsk13 properly installed?

**Comment by ekristen** [comment] 2019-04-05 18:04
Try uninstalling libtsk first. Might have to alter and publish a new version telling apt to replace it.

**Comment by ekristen** [comment] 2019-04-05 18:43
```
apt-get remove autopsy sleuthkit libtsk13 libtsk
```

then

```
apt-get install autopsy sleuthkit
```

I'll have to make an additional change to have libtsk13 replace libtsk.

**Comment by ekristen** [comment] 2019-04-07 17:17
@zappeee if you switch to the dev ppa of SIFT and confirm that libtsk is still installed, you can test upgrade by installing sleuthkit again. libtsk13 is now set to confict/replace libtsk.

**Comment by ekristen** [comment] 2019-04-07 17:17
I need to do a bit more testing, then I'll promote it to stable.

**Comment by zappeee** [comment] 2019-04-08 08:00
> ```
> apt-get remove autopsy sleuthkit libtsk13 libtsk
> ```
> then
> 
> ```
> apt-get install autopsy sleuthkit
> ```
> I'll have to make an additional change to have libtsk13 replace libtsk.

Thanks, that did the trick!

**Comment by zappeee** [comment] 2019-06-07 09:48
> I need to do a bit more testing, then I'll promote it to stable.

Was this promoted to stable?

**Comment by ekristen** [comment] 2019-07-06 15:51
I think this has been fixed?

**Comment by zappeee** [comment] 2019-07-08 06:34
> I think this has been fixed?

I haven't tested more than above.

**Comment by ekristen** [comment] 2019-08-17 17:35
I cannot reproduce on the latest version, closing out.

**Closed by ekristen** 2019-08-17 17:35 UTC
Labels: kind/bug
