### ISSUE TITLE
SIFT Workstation for Apple m2 

### ISSUE THREAD

**Issue by Chiller89** [teamdfir/sift#616] opened 2024-01-04 17:58 UTC

**Comment by Chiller89** [comment] 2024-01-04 18:01
Will there be a version for Mac OS M2 ?

**Comment by ekristen** [comment] 2024-01-04 18:42
Ideally yes, but not all tools work on ARM64 architecture which is why there's not a version for it yet.

**Comment by ekristen** [comment] 2024-09-17 15:21
Duplicate of #592

**Closed by ekristen** 2024-09-17 15:21 UTC
