### ISSUE TITLE
Error in timesketch installation

### ISSUE THREAD

**Issue by joejegan** [teamdfir/sift#430] opened 2020-02-04 00:29 UTC
I am getting the following error while installing SIFT

OS: Ubuntu 18.04
sift-cli@1.8.0
sift-version: v2020.1.0

Note that timesketch added dependency to sigmatools through a recent commit https://github.com/google/timesketch/commit/0c6c4b65a6c0f2051d074e87bbb2da2424fa6c35#diff-b4ef698db8ca845e5845c4618278f29a

Collecting sigmatools==0.14 (from timesketch)   Cache entry deserialization failed, entry ignored
  Cache entry deserialization failed, entry ignored
  Cache entry deserialization failed, entry ignored
  Could not find a version that satisfies the requirement sigmatools==0.14 (from timesketch) (from versions: )
No matching distribution found for sigmatools==0.14 (from timesketch)

**Comment by ekristen** [comment] 2020-02-11 04:05
Closing in favor of #432

**Closed by ekristen** 2020-02-11 04:05 UTC

**Comment by bedantmishra** [comment] 2020-02-12 03:53
With clean install and update before SIFT install. It is Windows WSL Ubuntu 18.04 App.

`>> Incomplete due to Failures -- Success: 546, Failure: 12

List of Failures (first 10 only)

 NOTE: First failure is generally the root cause.

 IMPORTANT: If opening a ticket, please include this information.

  - ID: timesketch
    SLS: sift.python-packages.timesketch
    Run#: 256
    Comment: Failed to install packages: timesketch. Error: Collecting timesketch
Downloading https://files.pythonhosted.org/packages/77/9a/8be4cec0365fb4bca1a4be9dea9300053528c74e2647343be63072643d91/timesketch-20200131.post3.tar.gz (8.9MB)
Collecting alembic==1.3.2 (from timesketch)
Downloading https://files.pythonhosted.org/packages/dc/6d/3c1411dfdcf089ec89ce5e2222deb2292f39b6b1a5911222e15af9fe5a92/alembic-1.3.2.tar.gz (1.1MB)
Collecting altair==3.3.0 (from timesketch)
Downloading https://files.pythonhosted.org/packages/1f/ef/1311cb19c78954ebf23842e6710cc2ecf4bd1966934ca3cd41f005b77221/altair-3.3.0-py2.py3-none-any.whl (603kB)
Collecting celery==4.4.0 (from timesketch)
Downloading https://files.pythonhosted.org/packages/47/53/6e2ccc87b18ddc582d2de31b3ed9144c72a68062659e9e4a68e19312d254/celery-4.4.0-py2.py3-none-any.whl (421kB)
Collecting cryptography==2.3 (from timesketch)
Downloading https://files.pythonhosted.org/packages/67/21/e79987f1f9abae42d666b1f89b4e78aa096acc00bbf97ad40d19b07b4a83/cryptography-2.3-cp27-cp27mu-manylinux1_x86_64.whl (2.1MB)
Collecting datasketch==1.5.0 (from timesketch)
Downloading https://files.pythonhosted.org/packages/aa/8a/75f8fce1aad302fe43533e806d769627dc3e115480ba962510945aba5039/datasketch-1.5.0-py2.py3-none-any.whl (72kB)
Requirement already satisfied: elasticsearch==6.3.1 in /usr/lib/python2.7/dist-packages (from timesketch)
Collecting Flask==1.1.1 (from timesketch)
Downloading https://files.pythonhosted.org/packages/9b/93/628509b8d5dc749656a9641f4caf13540e2cdec85276964ff8f43bbb1d3b/Flask-1.1.1-py2.py3-none-any.whl (94kB)
Collecting flask_bcrypt==0.7.1 (from timesketch)
Downloading https://files.pythonhosted.org/packages/1d/c0/6d4c04d007d72b355de24e7a223978d1a95732245f9e9becbf45d3024bf8/Flask-Bcrypt-0.7.1.tar.gz
Collecting flask_login==0.4.1 (from timesketch)
Downloading https://files.pythonhosted.org/packages/c1/ff/bd9a4d2d81bf0c07d9e53e8cd3d675c56553719bbefd372df69bf1b3c1e4/Flask-Login-0.4.1.tar.gz
Collecting flask_migrate==2.5.2 (from timesketch)
Downloading https://files.pythonhosted.org/packages/4b/22/d20a105f13c58fe590ef38ac59d5cabc1a917549ea8f90b0ca7b4e84f6be/Flask_Migrate-2.5.2-py2.py3-none-any.whl
Collecting flask_restful==0.3.7 (from timesketch)
Downloading https://files.pythonhosted.org/packages/17/44/6e490150ee443ca81d5f88b61bb4bbb133d44d75b0b716ebe92489508da4/Flask_RESTful-0.3.7-py2.py3-none-any.whl
Collecting flask_script==2.0.6 (from timesketch)
Downloading https://files.pythonhosted.org/packages/00/a4/cd587b2b19f043b65bf33ceda2f6e4e6cdbd0ce18d01a52b9559781b1da6/Flask-Script-2.0.6.tar.gz (43kB)
Collecting flask_sqlalchemy==2.4.1 (from timesketch)
Downloading https://files.pythonhosted.org/packages/1e/65/226d95466c75e34e291a76890ed0e27af2e46ab913002847856f11d4d59d/Flask_SQLAlchemy-2.4.1-py2.py3-none-any.whl
Collecting flask_wtf==0.14.2 (from timesketch)
Downloading https://files.pythonhosted.org/packages/60/3a/58c629472d10539ae5167dc7c1fecfa95dd7d0b7864623931e3776438a24/Flask_WTF-0.14.2-py2.py3-none-any.whl
Collecting google-auth==1.7.0 (from timesketch)
Downloading https://files.pythonhosted.org/packages/2f/81/d1e7d9974ba7c886f6d133a8baae18cb8d92b2d09bcc4f46328306825de0/google_auth-1.7.0-py2.py3-none-any.whl (74kB)
Collecting google_auth_oauthlib==0.4.1 (from timesketch)
Downloading https://files.pythonhosted.org/packages/7b/b8/88def36e74bee9fce511c9519571f4e485e890093ab7442284f4ffaef60b/google_auth_oauthlib-0.4.1-py2.py3-none-any.whl
Collecting gunicorn==19.10.0 (from timesketch)
Downloading https://files.pythonhosted.org/packages/5f/54/c15f2c243c19074cbf06ce6c48732d99aec825487f87e57e86e9a22990f2/gunicorn-19.10.0-py2.py3-none-any.whl (113kB)
Collecting neo4jrestclient==2.1.1 (from timesketch)
Downloading https://files.pythonhosted.org/packages/95/4c/df54ba57f5838fd1ae162462f81d589b8352c6aa17d5b2a7a42e8abba048/neo4jrestclient-2.1.1.tar.gz (73kB)
Collecting numpy==1.16.6 (from timesketch)
Downloading https://files.pythonhosted.org/packages/3a/5f/47e578b3ae79e2624e205445ab77a1848acdaa2929a00eeef6b16eaaeb20/numpy-1.16.6-cp27-cp27mu-manylinux1_x86_64.whl (17.0MB)
Collecting oauthlib==3.1.0 (from timesketch)
Downloading https://files.pythonhosted.org/packages/05/57/ce2e7a8fa7c0afb54a0581b14a65b56e62b5759dbc98e80627142b8a3704/oauthlib-3.1.0-py2.py3-none-any.whl (147kB)
Collecting pandas==0.24.2 (from timesketch)
Downloading https://files.pythonhosted.org/packages/db/83/7d4008ffc2988066ff37f6a0bb6d7b60822367dcb36ba5e39aa7801fda54/pandas-0.24.2-cp27-cp27mu-manylinux1_x86_64.whl (10.1MB)
Collecting PyJWT==1.7.1 (from timesketch)
Downloading https://files.pythonhosted.org/packages/87/8b/6a9f14b5f781697e51259d81657e6048fd31a113229cf346880bb7545565/PyJWT-1.7.1-py2.py3-none-any.whl
Requirement already satisfied: python_dateutil==2.8.1 in /usr/local/lib/python2.7/dist-packages (from timesketch)
Collecting PyYAML==5.3 (from timesketch)
Downloading https://files.pythonhosted.org/packages/3d/d9/ea9816aea31beeadccd03f1f8b625ecf8f645bd66744484d162d84803ce5/PyYAML-5.3.tar.gz (268kB)
Collecting redis==3.3.11 (from timesketch)
Downloading https://files.pythonhosted.org/packages/32/ae/28613a62eea0d53d3db3147f8715f90da07667e99baeedf1010eb400f8c0/redis-3.3.11-py2.py3-none-any.whl (66kB)
Collecting requests==2.21.0 (from timesketch)
Downloading https://files.pythonhosted.org/packages/7d/e3/20f3d364d6c8e5d2353c72a67778eb189176f08e873c9900e10c0287b84b/requests-2.21.0-py2.py3-none-any.whl (57kB)
Collecting sigmatools==0.14 (from timesketch) The directory '/home/sansforensics/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/sansforensics/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Could not find a version that satisfies the requirement sigmatools==0.14 (from timesketch) (from versions: )
No matching distribution found for sigmatools==0.14 (from timesketch)
You are using pip version 9.0.3, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
- ID: undefined
SLS: sift.python-packages
Run#: 290
Comment: One or more requisite failed: sift.python-packages.timesketch.timesketch
- ID: undefined
SLS: sift.server
Run#: 461
Comment: One or more requisite failed: sift.python-packages.sift-python-packages
- ID: sift-config-theme-gnome-shell-favorites
SLS: sift.config.user.theme_bionic
Run#: 505
Comment: Command "gsettings set org.gnome.shell favorite-apps "['gnome-terminal.desktop', 'firefox.desktop', 'org.gnome.Nautilus.desktop']"" run
- ID: sift-config-theme-gnome-launcher-position
SLS: sift.config.user.theme_bionic
Run#: 506
Comment: Command "gsettings set org.gnome.shell.extensions.dash-to-dock dock-position BOTTOM" run
- ID: undefined
SLS: sift.config.user.theme
Run#: 507
Comment: One or more requisite failed: sift.config.user.theme_bionic.sift-config-theme-gnome-shell-favorites, sift.config.user.theme_bionic.sift-config-theme-gnome-launcher-position
- ID: undefined
SLS: sift.config.user
Run#: 508
Comment: One or more requisite failed: sift.config.user.theme.sift-config-user-theme
- ID: Etc/UTC
SLS: sift.config.timezone
Run#: 509
Comment: An exception occurred in this state: Traceback (most recent call last):
File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1919, in call
**cdata['kwargs'])
File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1918, in wrapper
return f(*args, **kwargs)
File "/usr/lib/python2.7/dist-packages/salt/states/timezone.py", line 73, in system
if salt'timezone.get_hwclock' == 'localtime':
File "/usr/lib/python2.7/dist-packages/salt/modules/timezone.py", line 386, in get_hwclock
ret = _timedatectl()
File "/usr/lib/python2.7/dist-packages/salt/modules/timezone.py", line 54, in _timedatectl
raise CommandExecutionError(msg)
CommandExecutionError: timedatectl failed: Failed to create bus connection: No such file or directory

  - ID: samba-service-smbd
    SLS: sift.config.samba
    Run#: 558
    Comment: Service smbd failed to start
  - ID: samba-service-nmbd
    SLS: sift.config.samba
    Run#: 559
    Comment: Service nmbd failed to [start]`

[saltstack.log](https://github.com/teamdfir/sift/files/4189748/saltstack.log)
