### ISSUE TITLE
[CLI] Unable to update sift via Saltstack

### ISSUE THREAD

**Issue by brendancarey33** [teamdfir/sift#449] opened 2020-03-18 01:37 UTC
When performing a 'sudo sift upgrade' I receive an error.

List of Failures (first 10 only)

NOTE: First failure is generally the root cause.

IMPORTANT: If opening a ticket, please include this information.

      - ID: undefined
        SLS: undefined
        Run#: undefined
        Comment: undefined

Log:
more /var/cache/sift/cli/v2020.2.1/saltstack.log
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Guessing ID. The id can be explicitly set in /etc/salt/minion
[DEBUG   ] Found minion id from generate_minion_id(): siftworkstation
[DEBUG   ] Configuration file path: /etc/salt/minion
 [WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Grains refresh requested. Refreshing grains.
 [DEBUG   ] Reading configuration from /etc/salt/minion
 [DEBUG   ] Please install 'virt-what' to improve results of the 'virtual' grain.
 [DEBUG   ] Loading static grains from /etc/salt/grains
 [DEBUG   ] Determining pillar cache
 [DEBUG   ] LazyLoaded jinja.render
 [DEBUG   ] LazyLoaded yaml.render
 [DEBUG   ] LazyLoaded jinja.render
 [DEBUG   ] LazyLoaded yaml.render
 [DEBUG   ] LazyLoaded state.apply
 [DEBUG   ] LazyLoaded saltutil.is_running
 [DEBUG   ] LazyLoaded grains.get
 [DEBUG   ] LazyLoaded config.get
 [DEBUG   ] Popen(['git', 'version'], cwd=/etc/salt, universal_newlines=False, shell=None)
 [DEBUG   ] Popen(['git', 'version'], cwd=/etc/salt, universal_newlines=False, shell=None)
 [DEBUG   ] Updating roots fileserver cache
 [DEBUG   ] Gathering pillar data for state run
 [DEBUG   ] Determining pillar cache
 [DEBUG   ] LazyLoaded jinja.render
 [DEBUG   ] LazyLoaded yaml.render
 [DEBUG   ] Finished gathering pillar data for state run
 [INFO    ] Loading fresh modules for state activity
 [DEBUG   ] LazyLoaded jinja.render
 [DEBUG   ] LazyLoaded yaml.render
 [DEBUG   ] Could not find file 'salt://undefined.sls' in saltenv 'base'
 [DEBUG   ] Could not find file 'salt://undefined/init.sls' in saltenv 'base'
 [DEBUG   ] LazyLoaded yaml.output
local:
- No matching sls found for 'undefined' in env 'base'

Ubuntu 18.04 upgraded from 16,04. I upgraded via dist because I have a complex install with a cuckoo sandbox environment. Any help would be appreciated.

Attempted:
- Reinstall of SaltStack
- recreate saltstack minion
- all permissions checked
- repos reloaded

**Comment by ekristen** [comment] 2020-03-18 01:40
Send me the contents of /etc/os-release

**Comment by brendancarey33** [comment] 2020-03-18 01:43
@ekristen 
$ more /etc/os-release 
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

**Comment by brendancarey33** [comment] 2020-03-20 01:26
*UPDATE*
I downgraded to CLI 1.8.1. No change.

**Comment by ekristen** [comment] 2020-03-20 01:45
Please go back to 1.8.3 and provide me the full output of the CLI as well as the salt stack log file; clearly something is not being detected properly

**Comment by brendancarey33** [comment] 2020-03-20 02:01
@ekristen Thank you for the support. Its been a struggle to keep missing out on the SIFT updates since 2018.

[CLI]
sift-cli@1.8.3
sift-version: v2018.16.0

 downloading v2020.2.1
downloading sift-saltstack-v2020.2.1.tar.gz.asc
downloading sift-saltstack-v2020.2.1.tar.gz.sha256
downloading sift-saltstack-v2020.2.1.tar.gz.sha256.asc
downloading sift-saltstack-v2020.2.1.tar.gz
validating file sift-saltstack-v2020.2.1.tar.gz
validating signature for sift-saltstack-v2020.2.1.tar.gz.sha256
extracting update sift-saltstack-v2020.2.1.tar.gz
performing update v2020.2.1
Log file: /var/cache/sift/cli/v2020.2.1/saltstack.log
Incomplete due to Failures -- Success: 0, Failure: 1
List of Failures (first 10 only)

NOTE: First failure is generally the root cause.

IMPORTANT: If opening a ticket, please include this information.
ID: undefined
SLS: undefined
Run#: undefined
Comment: undefined

*SALTLOG (appears to be same as prior)*

[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: siftworkstation
[DEBUG   ] Configuration file path: /etc/salt/minion
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Grains refresh requested. Refreshing grains.
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Please install 'virt-what' to improve results of the 'virtual' grain.
[DEBUG   ] Loading static grains from /etc/salt/grains
[DEBUG   ] Determining pillar cache
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded state.apply
[DEBUG   ] LazyLoaded saltutil.is_running
[DEBUG   ] LazyLoaded grains.get
[DEBUG   ] LazyLoaded config.get
[DEBUG   ] Updating roots fileserver cache
[DEBUG   ] Gathering pillar data for state run
[DEBUG   ] Determining pillar cache
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] Finished gathering pillar data for state run
[INFO    ] Loading fresh modules for state activity
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] Could not find file 'salt://undefined.sls' in saltenv 'base'
[DEBUG   ] Could not find file 'salt://undefined/init.sls' in saltenv 'base'
[DEBUG   ] LazyLoaded yaml.output
local:
- No matching sls found for 'undefined' in env 'base'

**Comment by ekristen** [comment] 2020-03-20 02:04
I need this file please /var/cache/sift/cli/v2020.2.1/saltstack.log

**Comment by brendancarey33** [comment] 2020-03-20 02:12
@ekristen the SALTLOG above is the output. Apologies for the confusion.

**Comment by ekristen** [comment] 2020-03-20 02:12
I believe I’ve figured out what’s going on, just not sure why. Working on a fix

**Comment by brendancarey33** [comment] 2020-03-20 02:13
@ekristen Copy, thanks!

**Comment by ekristen** [comment] 2020-03-22 04:10
try -- https://github.com/teamdfir/sift-cli/releases/tag/v1.8.4

**Comment by brendancarey33** [comment] 2020-03-22 21:16
$ sudo sift upgrade
sift-cli@1.8.4
sift-version: v2018.16.0

downloading v2020.2.1
downloading sift-saltstack-v2020.2.1.tar.gz.asc
downloading sift-saltstack-v2020.2.1.tar.gz.sha256
downloading sift-saltstack-v2020.2.1.tar.gz.sha256.asc
downloading sift-saltstack-v2020.2.1.tar.gz
validating file sift-saltstack-v2020.2.1.tar.gz
validating signature for sift-saltstack-v2020.2.1.tar.gz.sha256
extracting update sift-saltstack-v2020.2.1.tar.gz
performing update v2020.2.1
Log file: /var/cache/sift/cli/v2020.2.1/saltstack.log

Update returned exit code not zero
Error: Update returned exit code not zero
    at ChildProcess.<anonymous> (/snapshot/sift-cli/sift-cli.js:529:23)
    at ChildProcess.emit (events.js:196:13)
    at maybeClose (internal/child_process.js:1011:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:268:5)

Log:
more /var/cache/sift/cli/v2020.2.1/saltstack.log
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: siftworkstation
[DEBUG   ] Configuration file path: /etc/salt/minion
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Grains refresh requested. Refreshing grains.
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Loading static grains from /etc/salt/grains
[DEBUG   ] Determining pillar cache
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded state.apply
[DEBUG   ] LazyLoaded direct_call.execute
[DEBUG   ] LazyLoaded saltutil.is_running
[DEBUG   ] LazyLoaded grains.get
[DEBUG   ] LazyLoaded config.get
[DEBUG   ] key: test, ret: _|-
[DEBUG   ] Updating roots fileserver cache
[DEBUG   ] Gathering pillar data for state run
[DEBUG   ] Determining pillar cache
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] Finished gathering pillar data for state run
[INFO    ] Loading fresh modules for state activity
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] Could not find file 'salt://undefined.sls' in saltenv 'base'
[DEBUG   ] Could not find file 'salt://undefined/init.sls' in saltenv 'base'
[DEBUG   ] LazyLoaded yaml.output
local:
- No matching sls found for 'undefined' in env 'base'

- I did do an update prior. Nothing to autoremove or update. Is it possible im missing a repository?

**Comment by ekristen** [comment] 2020-03-22 23:06
Try adding —mode=desktop

**Comment by brendancarey33** [comment] 2020-03-22 23:47
Same errors/outputs.

I also tried manually installing the specific version as per the help, but it just returns the usage page.

**Comment by ekristen** [comment] 2020-03-23 14:04
I found the bug.

**Comment by ekristen** [comment] 2020-03-23 14:07
https://github.com/teamdfir/sift-cli/releases/tag/v1.8.5

**Comment by brendancarey33** [comment] 2020-03-23 17:29
Possible progress. Updated using sift upgrade --mode=desktop. A large number of updates appeared to run, even received new posters. Ended with the error below. May have updated, but "sift version" does not indicate it. 

Event error:
Running: sift-config-tools
Update returned exit code not zero
Error: Update returned exit code not zero
    at ChildProcess.<anonymous> (/snapshot/sift-cli/sift-cli.js:529:23)
    at ChildProcess.emit (events.js:196:13)
    at maybeClose (internal/child_process.js:1011:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:268:5)

cuckoo@siftworkstation: ~
$ sift version
sift-cli@1.8.5
sift-version: v2018.16.0
mode: complete

Log much larger. I have attached it.

[saltstack.log](https://github.com/teamdfir/sift/files/4370965/saltstack.log)

**Comment by ekristen** [comment] 2020-03-23 17:58
@brendancarey33 honestly the scenario of 16.04 -> 18.04 hasn't been tested. It looks like there are just a lot of general failures to upgrade packages, this could be for a number of reasons outside the control of me and SIFT and the tooling.

I would start by running apt-get update && apt-get upgrade manually and make sure apt is healthy and happy and everything is up-to-date. After that you can try running `sift upgrade` again.

The SIFT cli is a simply proxy for running saltstack to configure the host properly, 90% of the configuration is just apt-get install commands.

**Comment by brendancarey33** [comment] 2020-03-23 18:01
@ekristen Copy. I did notice when I ran apt-get update//upgrade a lot of things did update. Hopefully, I can help figure it out. Let me know if you'd still like bug reports pertaining to this, otherwise, I can keep awaiting new CLI updates and see if something clicks later on.

**Comment by Fetchered** [comment] 2020-04-01 12:53
@ekristen @brendancarey33 I came across the error that's listed in the saltstack yesterday, and it came about because I already had rekall installed. I did a pip uninstall rekall -y, then rm /usr/local/bin/rek* then sudo sift upgrade and there was no issue.
The issue listed in the saltstack log said it was unable to create the symlink for rekall, likely because the binaries already existed in the /usr/local/bin directory.

That's what fixed the particular issue you're seeing at this point.

**Comment by brendancarey33** [comment] 2020-04-01 22:42
@Fetchered I tried that, got reminded I didn't have it installed. However, looked like a possible issue with lvm2, force uninstalled and attempted to sift upgrade. It ran through and ended with the _exit code error_ previously identified. I'm starting to wonder if it IS in fact upgraded, but the CLI output is not upgrading due to a cache issue. Thanks for the tip, I think your on to something.

**Comment by Fetchered** [comment] 2020-04-01 23:12
The /etc/sift* files are what tracks the "installation" part of it. Another thought might be to rename them to ".old", fix the rekall binaries (above) and then do a sudo sift install.

**Comment by brendancarey33** [comment] 2020-04-02 00:52
Thanks for all the help, but I think its deep somewhere and not likely identified. I downgraded to 1.8.5 (I was not getting this on a working 1.8.6 master by @ekristen) I got a stop on "sift-config-tools" so I tried your rekall technique but no go. see below. I think its just not going to work from an upgrade from 16.04.

Update returned exit code not zero
Error: Update returned exit code not zero
    at ChildProcess.<anonymous> (/snapshot/sift-cli/sift-cli.js:529:23)
    at ChildProcess.emit (events.js:196:13)
    at maybeClose (internal/child_process.js:1011:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:268:5)

**Comment by Fetchered** [comment] 2020-04-02 01:42
If you take a look in the saltstack.log file and do a search for 'result: false' (not the space between the colon and false), you'll see where the failure is. You might see it three or four times, likely all centered around rekall or python. 
It is possible to upgrade from 16.04, I've done it before, it just takes a little finessing at times. If you want to submit your saltstack.log from this go 'round, I can take a quick peek as well.

**Comment by ekristen** [comment] 2020-04-02 01:47
Thanks @Fetchered for helping out! I definitely need the saltstack.log to pinpoint what's failing.

**Comment by brendancarey33** [comment] 2020-04-02 02:37
@ekristen @Fetchered I should clarify, I am unsure of the challenges of upgrading with a cuckoo user/sandbox setup. too many variables between them I think. However, please see my saltlog below.
[saltstack.log](https://github.com/teamdfir/sift/files/4418619/saltstack.log)

**Comment by digitalsleuth** [comment] 2020-06-02 01:50
Apologies for not getting back to you sooner, I let this get away from me (I am/was Fetchered). @brendancarey33 Your installation issue primarily only seemed to be rekall, and it appeared that since rekall was already installed on your system, the SIFT installer was unable to create a symlink in the optimal location, because a file with the intended destination already existed.

If you're still in the same situation, you can uninstall or manually remove the rekall binaries (symlinks) from /usr/bin or /usr/local/bin and run the installer again (not the desired method).

However, I would recommend downloading the newest cli and running the install again, and this time try using the --pre-release option to see if this fixes some of your issues. The final issue located at the end of the saltstack.log file about not finding a pip binary should be resolved by both the newest CLI and the --pre-release option.

Cheers

**Comment by brendancarey33** [comment] 2020-06-02 02:26
I appreciate the support @digitalsleuth! I will apply fixes and promptly report. As someone who makes about %15 of their income off this suite, I knew I was safe with all the support from you and @ekristen, but felt uneasy at times. I will reply soon with fix results.

**Comment by brendancarey33** [comment] 2020-06-03 22:31
@digitalsleuth Tried both the update and the --pre-release tag (as well as other modes) and I am still getting some sort of error. It appears the log is quite a bit larger than previously, so I was unable to try and find the issue myself or see if it was still due to rekall. Again, I appreciate any help (knowing I should just operate on a new install), but my cuckoo config is just so bloated I cant separate them. I have attached the log if it is of any value. (I ran both scenarios
 as sansforensics and cuckoo users)
[saltstack.log](https://github.com/teamdfir/sift/files/4726525/saltstack.log)

**Comment by digitalsleuth** [comment] 2020-06-03 22:48
Got the log, but not at a computer at the moment. Will reply when I get home. Cheers.

**Comment by ekristen** [comment] 2020-06-05 14:47
There's a new pre-release out too. We've been suffering a lot of python issues unfortunately and still have not tracked down the root cause. Something that works perfectly for @digitalsleuth doesn't work for me and visa-versa. 

Appreciate the assist @digitalsleuth

**Comment by brendancarey33** [comment] 2020-06-14 05:11
I get hung up on "Running: cpan install HTML::QuickTable" when trying updates. FYI

**Comment by digitalsleuth** [comment] 2020-06-14 11:17
@brendancarey33 We've identified the issue with the cpan install command. It should be fixed in the next release.

**Comment by ekristen** [comment] 2020-07-09 13:49
@brendancarey33 the pre-release is working at the moment

**Comment by ekristen** [comment] 2020-07-09 13:52
https://github.com/teamdfir/sift-saltstack/releases/tag/v2020.7.0 -- with fixes above.

**Closed by ekristen** 2020-07-09 13:52 UTC
