### ISSUE TITLE
Unable to update sift

### ISSUE THREAD

**Issue by netfoo** [teamdfir/sift#427] opened 2020-02-01 11:02 UTC
$ sudo sift update
> sift-cli@1.8.0
> sift-version: v2018.16.0

> downloading v2018.16.0
>> downloading sift-saltstack-v2018.16.0.tar.gz.asc
>> downloading sift-saltstack-v2018.16.0.tar.gz.sha256
>> downloading sift-saltstack-v2018.16.0.tar.gz.sha256.asc
>> downloading sift-saltstack-v2018.16.0.tar.gz
> validating file sift-saltstack-v2018.16.0.tar.gz
> validating signature for sift-saltstack-v2018.16.0.tar.gz.sha256
> extracting update sift-saltstack-v2018.16.0.tar.gz
> performing update v2018.16.0
>> Log file: /var/cache/sift/cli/v2018.16.0/saltstack.log

>> Incomplete due to Failures -- Success: 0, Failure: 1

>>>> List of Failures (first 10 only)

     NOTE: First failure is generally the root cause.

     IMPORTANT: If opening a ticket, please include this information.

      - ID: undefined
        SLS: undefined
        Run#: undefined
        Comment: undefined

tail -f ./saltstack.log
tail: saltstack.log: file truncated
[DEBUG   ] Missing configuration file: /etc/salt/minion
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: siftworkstation
# [DEBUG   ] Configuration file path: /etc/salt/minion
# [WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
# [DEBUG   ] Grains refresh requested. Refreshing grains.
# [DEBUG   ] Missing configuration file: /etc/salt/minion
# [DEBUG   ] Please install 'virt-what' to improve results of the 'virtual' grain.
# [DEBUG   ] Loading static grains from /etc/salt/grains
# [DEBUG   ] Determining pillar cache
# [DEBUG   ] LazyLoaded jinja.render
# [DEBUG   ] LazyLoaded yaml.render
# [DEBUG   ] LazyLoaded jinja.render
# [DEBUG   ] LazyLoaded yaml.render
# [DEBUG   ] LazyLoaded state.apply
# [DEBUG   ] LazyLoaded saltutil.is_running
# [DEBUG   ] LazyLoaded grains.get
# [DEBUG   ] LazyLoaded config.get
# [DEBUG   ] Updating roots fileserver cache
# [DEBUG   ] Gathering pillar data for state run
# [DEBUG   ] Determining pillar cache
# [DEBUG   ] LazyLoaded jinja.render
# [DEBUG   ] LazyLoaded yaml.render
# [DEBUG   ] Finished gathering pillar data for state run
# [INFO    ] Loading fresh modules for state activity
# [DEBUG   ] LazyLoaded jinja.render
# [DEBUG   ] LazyLoaded yaml.render
# [DEBUG   ] Could not find file 'salt://sift/desktop.sls' in saltenv 'base'
# [DEBUG   ] Could not find file 'salt://sift/desktop/init.sls' in saltenv 'base'
# [DEBUG   ] LazyLoaded yaml.output
local:
- No matching sls found for 'sift.desktop' in env 'base'

**Comment by Fetchered** [comment] 2020-02-05 03:16
Was having the same issue, using 1.8.1-rc2. Reverted back to rc1, didn't work. However, then reverted back to 1.8.0 and was able to upgrade with no failures. Downloaded 1.8.1-rc2 and upgraded again, no issues. Unsure of the cause, however.

**Comment by ekristen** [comment] 2020-02-05 03:19
Run upgrade not update, poor UX design on my part. 

I need to change it to like upgrade and dist-upgrade. 

2018.x.x anything is old, please upgrade.

16.04 is busted at the moment, 18.04 is good to go? 

Erik

**Comment by Fetchered** [comment] 2020-02-05 03:23
With 1.8.1-rc's 1 and 2, both update and upgrade were giving me the same error as netfoo referenced above. Had to go to 1.8.0, did update (and upgrade), both succeeded without failure. Then downloaded 1.8.1-rc2 directly and did both update and upgrade, both succeeded without failure. All in 18.04. Version prior to the error was 1.8.0 and 2019.03.01-rc7. All is good now.

**Comment by ekristen** [comment] 2020-02-05 03:25
Upgrade shouldn’t but update would not as 2018 wouldn’t be supported by the 1.8.x version.

Upgrade should absolutely work.

**Comment by Fetchered** [comment] 2020-02-05 03:30
Correct, I should clarify, my issue varies only slightly from above. I received the same error starting from 2019.03.01-rc7, where netfoo received their error from 2018.16.0. 
$ sudo sift update
> sift-cli@1.8.1-rc1
> sift-version: v2019.03.01-rc7

> downloading v2019.03.01-rc7
>> downloading sift-saltstack-v2019.03.01-rc7.tar.gz.asc
>> downloading sift-saltstack-v2019.03.01-rc7.tar.gz.sha256
>> downloading sift-saltstack-v2019.03.01-rc7.tar.gz.sha256.asc
>> downloading sift-saltstack-v2019.03.01-rc7.tar.gz
> validating file sift-saltstack-v2019.03.01-rc7.tar.gz
> validating signature for sift-saltstack-v2019.03.01-rc7.tar.gz.sha256
> extracting update sift-saltstack-v2019.03.01-rc7.tar.gz
> performing update v2019.03.01-rc7
>> Log file: /var/cache/sift/cli/v2019.03.01-rc7/saltstack.log


>> Incomplete due to Failures -- Success: 0, Failure: 1

>>>> List of Failures (first 10 only)

     NOTE: First failure is generally the root cause.

     IMPORTANT: If opening a ticket, please include this information.

      - ID: undefined
        SLS: undefined
        Run#: undefined
        Comment: undefined
`
`
$ sudo sift upgrade
> sift-cli@1.8.1-rc1
> sift-version: v2019.03.01-rc7

> downloading v2020.1.0
>> downloading sift-saltstack-v2020.1.0.tar.gz.asc
>> downloading sift-saltstack-v2020.1.0.tar.gz.sha256
>> downloading sift-saltstack-v2020.1.0.tar.gz.sha256.asc
>> downloading sift-saltstack-v2020.1.0.tar.gz
> validating file sift-saltstack-v2020.1.0.tar.gz
> validating signature for sift-saltstack-v2020.1.0.tar.gz.sha256
> extracting update sift-saltstack-v2020.1.0.tar.gz
> performing update v2020.1.0
>> Log file: /var/cache/sift/cli/v2020.1.0/saltstack.log


>> Incomplete due to Failures -- Success: 0, Failure: 1

>>>> List of Failures (first 10 only)

     NOTE: First failure is generally the root cause.

     IMPORTANT: If opening a ticket, please include this information.

      - ID: undefined
        SLS: undefined
        Run#: undefined
        Comment: undefined

$ sudo sift upgrade
> sift-cli@1.8.1-rc2
> sift-version: v2019.03.01-rc7

> downloading v2020.1.0
>> downloading sift-saltstack-v2020.1.0.tar.gz.asc
>> downloading sift-saltstack-v2020.1.0.tar.gz.sha256
>> downloading sift-saltstack-v2020.1.0.tar.gz.sha256.asc
>> downloading sift-saltstack-v2020.1.0.tar.gz
> validating file sift-saltstack-v2020.1.0.tar.gz
> validating signature for sift-saltstack-v2020.1.0.tar.gz.sha256
> extracting update sift-saltstack-v2020.1.0.tar.gz
> performing update v2020.1.0
>> Log file: /var/cache/sift/cli/v2020.1.0/saltstack.log


>> Incomplete due to Failures -- Success: 0, Failure: 1

>>>> List of Failures (first 10 only)

     NOTE: First failure is generally the root cause.

     IMPORTANT: If opening a ticket, please include this information.

      - ID: undefined
        SLS: undefined
        Run#: undefined
        Comment: undefined

**Comment by ekristen** [comment] 2020-02-05 03:31
Please attach the salt stack log if you haven’t already done so.

**Comment by Fetchered** [comment] 2020-02-05 03:35
[saltstack.log](https://github.com/teamdfir/sift/files/4157295/saltstack.log)
This is the 2019.03.01 which started the error, but since I managed to workaround the issue, the latest saltstack.log's do not have any failures.

**Comment by ekristen** [comment] 2020-02-11 04:21
Please upgrade to the latest version of the CLI, and then install the latest or upgrade to the latest version of SIFT.

**Comment by Fetchered** [comment] 2020-02-12 02:23
Will do, just getting to my e-mails now, so I'll do that in the next few
minutes.

Cheers

**Comment by ekristen** [comment] 2020-02-28 15:33
@Fetchered can we close this?

**Comment by Fetchered** [comment] 2020-02-29 19:20
Running the update with the newest cli right now. Need a few minutes.

**Comment by Fetchered** [comment] 2020-02-29 19:28
Update and upgrade ran and completed with no errors. This can be closed as far as I'm concerned. Sorry for the late reply!

**Closed** 2020-05-06 19:46 UTC
Labels: status/waiting-feedback, wontfix
